name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn typecheck

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn format
